### PR TITLE
Correction of some typos, added Windows build script.

### PR DESCRIPTION
**Pull request by waltje**
This PR just corrects some typos in README.md, and it adds a build script for Windows systems.

### CODE REVIEW

**Comment by ekuester** [comment]
@walltje
.thanks for correction of typos and build script. Gives the corrected .asm file same .bin result as i published? I have to test it... Are you still involved in "playing" with SC/MP? Regards, Erich Kuester

**Comment by ekuester** [comment]
Revised .asm file give identical result results, so merge is accepted. Thanks!

**Comment by waltje** [comment]
Yes, I am still (again) using the SC/MP, in both some of my SBC boards, as well as my emulator (which matches those boards.)

More updates will come soon!

**Comment by ekuester** [comment]
@waltje,
do you have the possibility to test the NIBLFP on your systems, be it on real hardware or the mentioned emulator? I am very curious to see if my code will work... I had written in those times a monitor for the Elektor-SC/MP that I brought to life again, but due to lack of a real system can not test. Binary code and assembly listing is now available and I plan to add it to my repository.
I am in contact with two other SC/MP-enthusiasts, see [site of Ronald Dekker](https://www.dos4ever.com/SCMP/SCMP.html) and [site of Michael Haardt](http://www.moria.de/) .

**Comment by waltje** [comment]
Send me an email .. I have a few questions for you.
--Fred

    On Wednesday, June 28, 2023 at 04:32:25 PM EDT, Erich Küster ***@***.***> wrote:  
 
 


@waltje,
do you have the possibility to test the NIBLFP on your systems, be it on real hardware or the mentioned emulator? I am very curious to see if my code will work... I had written in those times a monitor for the Elektor-SC/MP that I brought to life again, but due to lack of a real system can not test. Binary code and assembly listing is now available and I plan to add it to my repository.
I am in contact with two other SC/MP-enthusiasts, see site of Ronald Dekker and site of Michael Haardt .

**Pull request merged**
